### ISSUE TITLE
! Undefined control sequence. <argument> \luatexversion

### ISSUE THREAD

**Issue by luciole135** [agrahn/media9#2]
Hi, 
This fatal error occurred:
`("C:\Program Files\MiKTeX 2.9\tex\latex\media9\pdfbase.sty"
Package: pdfbase 2017/03/23 v0.14 driver independent access to low-level PDF fe
atures
\g_pbs_page_int=\count309

! Undefined control sequence.
<argument> \luatexversion 
                          <95
l.924 }
       
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

! Missing number, treated as zero.
<to be read again> 
                   <
l.924 }
       
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)

\g_pbs_oc_int=\count310
)`

by compiling this document that I copied from the documentation of your package
```
\documentclass{beamer}

\usepackage{media9}
\begin{document}
\begin{frame}{Video}
\addmediapath{C:/Users/Perso/Downloads/}
\includemedia[
  width=0.4\linewidth,
  totalheight=0.225\linewidth,
  addresource=random.mp4,
  activate=pagevisible,
  passcontext,  %show VPlayer's right-click menu
  flashvars={
    source=random.mp4
    &autoPlay=true
  }
]{\fbox{Click!}}{VPlayer.swf}


\end{frame}
\end{document}
```
can you correct it?

**Comment by agrahn** [comment]
Already done yesterday, 2017/07/24.
